/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Billing;

import customerManager.createAccount;
import java.awt.GridLayout;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import customerManager.menu;


/**
 *
 * @author Admin
 */
public class productGUI extends javax.swing.JFrame {

    /**
     * Creates new form productGUI
     */
    public productGUI() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    ////////////////////////////////////////////////////////////////////////
    
    
 


      
  
        public void setTable(ArrayList<Object[]> tableData) {
        // Tạo một DefaultTableModel mới
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        // Thêm các cột vào model nếu có dữ liệu
        if (tableData != null && !tableData.isEmpty()) {
           
            
    
            for (Object[] row : tableData) {
                model.addRow(row);
            }
        }
        ItemCost();
        Change();
    }

       
  public void setCustomerName(String name) {
        customerNameF.setText(name);
    }
  public void setComboBox(String name){
      jcboPayment.setSelectedItem(name);
  }
  public void setCash(String name){
      jtxtDisplay.setText(name);
  }
public void setPaidCheck(boolean state){
    PaidCheck.setSelected(state);
    
}
       
 
   
    
    
    public void ItemCost()
    {   
        
        
        int amount;
        double sum=0;
        for(int i=0;i<jTable1.getRowCount();i++){
          amount=Integer.parseInt(jTable1.getValueAt(i, 3).toString());
         sum=sum+(Double.parseDouble(jTable1.getValueAt(i, 2).toString()))*amount;
        }
        PreparedStatement pstmt=null;
        Connection conn=null;
        ResultSet rs=null;
           double discount=0;
         try{

          double total=0;
          int customerID;        
          String cusName=customerNameF.getText();
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         String url = "jdbc:sqlserver://localhost:1433;databaseName=MOONHOUSE;user=sa;password=123456;encrypt=true;trustServerCertificate=true";
          conn = DriverManager.getConnection(url);
        String CalculationDiscount = "SELECT Total_Price FROM CUSTOMER " +
                              "JOIN invoices " +
                              "ON CUSTOMER.customerID = invoices.customerID " +
                              "WHERE CUSTOMER.Name=?";
         
         pstmt=conn.prepareStatement(CalculationDiscount);
         pstmt.setString(1,cusName);
         
         rs=pstmt.executeQuery();
        
         if(rs.next()){
         
     do{
      double billAmount=rs.getDouble("Total_Price");
      total+=billAmount; 
       }
     
     
     while(rs.next());
     
     
     if(total>=500)
     {
     discount=0.03;
     }
     
     if(total>=1000)
     {
         discount=0.05;
     }
     
     if (total>=2000){
         discount=0.06;
     }
     
       if (total>=3000){
         discount=0.06;
     }
     if(total>=5000){
         discount=0.08;
     }
     
         }
         else
         {   
            discount=0; 
         }
         }
         catch (ClassNotFoundException | SQLException e) {
                e.printStackTrace();
        }
         String iDiscount=String.format("£%.2f",discount);
         jtxtDiscount.setText(iDiscount);
       jtxtSubTotal.setText(Double.toString(sum));
       double cTotal=Double.parseDouble(jtxtSubTotal.getText());
       
       double cTax=(cTotal * 3.9)/100;
       String iTaxTotal=String.format("£%.2f",cTax);
       jtxtTax.setText(iTaxTotal);
       
        String iSubTotal=String.format("£%.2f",cTotal);
       jtxtSubTotal.setText(iSubTotal);
       DecimalFormat decimalFormat = new DecimalFormat("#.##"); 
       double totalValue = (cTax + cTotal)-(cTax + cTotal)*discount;
       String totalFormatted = decimalFormat.format(totalValue);
     
       jtxtTotal.setText(totalFormatted);
       
       String BarCode=String.format("total is %.2f", cTotal +cTax);
       jtxtBarCode.setText(BarCode);
    
    }
    
    public void Change()
    {  
     
       int amount;
       double sum=0;
       double tax=3.9;
       double cash=Double.parseDouble(jtxtDisplay.getText());
        for(int i=0;i<jTable1.getRowCount();i++)
            
        {amount=Integer.parseInt(jTable1.getValueAt(i, 3).toString());
         sum=sum+Double.parseDouble(jTable1.getValueAt(i, 2).toString())*amount;
        }
        
     double total=Double.parseDouble(jtxtTotal.getText());
        double cChange=cash-total;
    
     
        String ChangeGiven=String.format("£ %.2f", cChange);
        jtxtChange.setText(ChangeGiven);
       
        
    }
    
    

    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnlist = new javax.swing.JPanel();
        bathroomAccessoriesBtn = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jbtn2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        PaidCheck = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtDiscount = new javax.swing.JTextField();
        discountLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jbtnRemove = new javax.swing.JButton();
        jtbtnPay = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        customerNameF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jtxtBarCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnlist.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroup1.add(bathroomAccessoriesBtn);
        bathroomAccessoriesBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        bathroomAccessoriesBtn.setText("bathroom accessories");
        bathroomAccessoriesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bathroomAccessoriesBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jRadioButton2.setText("living room decor");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jRadioButton3.setText("kitchenware");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnlistLayout = new javax.swing.GroupLayout(btnlist);
        btnlist.setLayout(btnlistLayout);
        btnlistLayout.setHorizontalGroup(
            btnlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnlistLayout.createSequentialGroup()
                .addGroup(btnlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnlistLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bathroomAccessoriesBtn)
                        .addGap(16, 16, 16))
                    .addGroup(btnlistLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(1179, 1179, 1179))
            .addGroup(btnlistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnlistLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bathroomAccessoriesBtn, jRadioButton2});

        btnlistLayout.setVerticalGroup(
            btnlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnlistLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(bathroomAccessoriesBtn)
                .addGap(82, 82, 82)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnlistLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bathroomAccessoriesBtn, jRadioButton2, jRadioButton3});

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnlist, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.setMaximumSize(new java.awt.Dimension(75, 75));
        jbtn2.setMinimumSize(new java.awt.Dimension(75, 75));
        jbtn2.setPreferredSize(new java.awt.Dimension(110, 110));
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jButton3.setText(".");
        jButton3.setMaximumSize(new java.awt.Dimension(75, 75));
        jButton3.setMinimumSize(new java.awt.Dimension(75, 75));
        jButton3.setPreferredSize(new java.awt.Dimension(110, 110));
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        jbtn1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.setMaximumSize(new java.awt.Dimension(75, 75));
        jbtn1.setMinimumSize(new java.awt.Dimension(75, 75));
        jbtn1.setPreferredSize(new java.awt.Dimension(110, 110));
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        jbtn7.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.setMaximumSize(new java.awt.Dimension(75, 75));
        jbtn7.setMinimumSize(new java.awt.Dimension(75, 75));
        jbtn7.setPreferredSize(new java.awt.Dimension(110, 110));
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jbtn8.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.setMaximumSize(new java.awt.Dimension(75, 75));
        jbtn8.setMinimumSize(new java.awt.Dimension(75, 75));
        jbtn8.setPreferredSize(new java.awt.Dimension(110, 110));
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        jbtn9.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.setMaximumSize(new java.awt.Dimension(75, 75));
        jbtn9.setMinimumSize(new java.awt.Dimension(75, 75));
        jbtn9.setPreferredSize(new java.awt.Dimension(110, 110));
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        jbtn4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.setMaximumSize(new java.awt.Dimension(75, 75));
        jbtn4.setMinimumSize(new java.awt.Dimension(75, 75));
        jbtn4.setPreferredSize(new java.awt.Dimension(110, 110));
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jbtnC.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.setMaximumSize(new java.awt.Dimension(75, 75));
        jbtnC.setMinimumSize(new java.awt.Dimension(75, 75));
        jbtnC.setPreferredSize(new java.awt.Dimension(110, 110));
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        jbtn5.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.setMaximumSize(new java.awt.Dimension(75, 75));
        jbtn5.setMinimumSize(new java.awt.Dimension(75, 75));
        jbtn5.setPreferredSize(new java.awt.Dimension(110, 110));
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jbtn0.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.setMaximumSize(new java.awt.Dimension(75, 75));
        jbtn0.setMinimumSize(new java.awt.Dimension(75, 75));
        jbtn0.setPreferredSize(new java.awt.Dimension(110, 110));
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        jbtn6.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.setMaximumSize(new java.awt.Dimension(75, 75));
        jbtn6.setMinimumSize(new java.awt.Dimension(75, 75));
        jbtn6.setPreferredSize(new java.awt.Dimension(110, 110));
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jbtn3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.setMaximumSize(new java.awt.Dimension(75, 75));
        jbtn3.setMinimumSize(new java.awt.Dimension(75, 75));
        jbtn3.setPreferredSize(new java.awt.Dimension(110, 110));
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Category", "Quality", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel4.setText("Change");

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel5.setText("Payment method");

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel6.setText("Cash");

        jtxtDisplay.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });

        jtxtChange.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jtxtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChangeActionPerformed(evt);
            }
        });

        jcboPayment.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cash", "visa card", "master card", " " }));
        jcboPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboPaymentActionPerformed(evt);
            }
        });

        PaidCheck.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        PaidCheck.setText("Paid");
        PaidCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PaidCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PaidCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaidCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtDisplay)
                            .addComponent(jcboPayment, 0, 262, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(jtxtChange, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(PaidCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel5)
                    .addContainerGap(348, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jcboPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PaidCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel5)
                    .addContainerGap(243, Short.MAX_VALUE)))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("subTotal");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setText("Total");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setText("Tax");

        jtxtTotal.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });

        jtxtSubTotal.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });

        jtxtTax.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N

        jtxtDiscount.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N

        discountLabel.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        discountLabel.setText("Discount");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(discountLabel))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountLabel)
                    .addComponent(jtxtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbtnRemove.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jbtnRemove.setText("REMOVE");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });

        jtbtnPay.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jtbtnPay.setText("PAY");
        jtbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnPayActionPerformed(evt);
            }
        });

        jbtnPrint.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jbtnPrint.setText("PRINT");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jbtnExit.setText("EXIT");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jbtnReset.setText("RESET");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jtbtnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtnRemove)
                                    .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jbtnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbtnPay)
                    .addComponent(jbtnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPrint)
                    .addComponent(jbtnRemove))
                .addGap(31, 31, 31)
                .addComponent(jbtnExit)
                .addGap(25, 25, 25))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel7.setText("Customer Name:");

        customerNameF.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        customerNameF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(customerNameF, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(customerNameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        jButton1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jButton1.setText(" BACK TO THE MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(251, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(6185, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        jtxtBarCode.setFont(new java.awt.Font("Segoe MDL2 Assets", 1, 12)); // NOI18N
        jtxtBarCode.setText("DASDSADSADASDADDDDDDDDDAAAAAAAAjj");
        jtxtBarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBarCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                            .addComponent(jtxtBarCode))
                        .addGap(94, 94, 94)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtBarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 165, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtBarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBarCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBarCodeActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
      String Enternumber = jtxtDisplay.getText();
     if(Enternumber == "")
     {
         jtxtDisplay.setText(jbtn8.getText());
     }
     else
     {
      Enternumber=jtxtDisplay.getText()+ jbtn8.getText(); 
      jtxtDisplay.setText(Enternumber);
        
     }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
       String Enternumber = jtxtDisplay.getText();
     if(Enternumber == "")
     {
         jtxtDisplay.setText(jbtn9.getText());
     }
     else
     {
      Enternumber=jtxtDisplay.getText()+ jbtn9.getText(); 
      jtxtDisplay.setText(Enternumber);
        
     }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
       String Enternumber = jtxtDisplay.getText();
     if(Enternumber == "")
     {
         jtxtDisplay.setText(jbtn4.getText());
     }
     else
     {
      Enternumber=jtxtDisplay.getText()+ jbtn4.getText(); 
      jtxtDisplay.setText(Enternumber);
        
     }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String Enternumber = jtxtDisplay.getText();
     if(Enternumber == "")
     {
         jtxtDisplay.setText(jbtn5.getText());
     }
     else
     {
      Enternumber=jtxtDisplay.getText()+ jbtn5.getText(); 
      jtxtDisplay.setText(Enternumber);
        
     }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String Enternumber = jtxtDisplay.getText();
     if(Enternumber == "")
     {
         jtxtDisplay.setText(jbtn6.getText());
     }
     else
     {
      Enternumber=jtxtDisplay.getText()+ jbtn6.getText(); 
      jtxtDisplay.setText(Enternumber);
        
     }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
      String Enternumber = jtxtDisplay.getText();
     if(Enternumber == "")
     {
         jtxtDisplay.setText(jbtn1.getText());
     }
     else
     {
      Enternumber=jtxtDisplay.getText()+ jbtn1.getText(); 
      jtxtDisplay.setText(Enternumber);
        
     }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
       String Enternumber = jtxtDisplay.getText();
     if(Enternumber == "")
     {
         jtxtDisplay.setText(jbtn2.getText());
     }
     else
     {
      Enternumber=jtxtDisplay.getText()+ jbtn2.getText(); 
      jtxtDisplay.setText(Enternumber);
        
     }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
      String Enternumber = jtxtDisplay.getText();
     if(Enternumber == "")
     {
         jtxtDisplay.setText(jbtn3.getText());
     }
     else
     {
      Enternumber=jtxtDisplay.getText()+ jbtn3.getText(); 
      jtxtDisplay.setText(Enternumber);
        
     }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
     String Enternumber = jtxtDisplay.getText();
     if(Enternumber == "")
     {
         jtxtDisplay.setText(jbtn0.getText());
     }
     else
     {
      Enternumber=jtxtDisplay.getText()+ jbtn0.getText(); 
      jtxtDisplay.setText(Enternumber);
        
     }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtDisplay.setText("");
        jtxtChange.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jtbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnPayActionPerformed
       if(jcboPayment.getSelectedItem().equals("cash"))
       {
           Change(); 
       }
       else
       {
 
           jtxtChange.setText("");
           jtxtDisplay.setText("");
       }
    }//GEN-LAST:event_jtbtnPayActionPerformed

    private void jcboPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboPaymentActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarCode.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed



    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed

          Connection conn = null;
            PreparedStatement pstmt = null;
            Statement statement = null;
            ResultSet rs = null;
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433;databaseName=MOONHOUSE;user=sa;password=123456;encrypt=true;trustServerCertificate=true";
                conn = DriverManager.getConnection(url);           
                String findID = "SELECT invoice_id FROM invoices";
                statement = conn.createStatement();
                rs = statement.executeQuery(findID); 
                int id = 0;
                int previousID = 0;
                int nextid;
                int previousid = 0;
                boolean check = true;
                if (!rs.next()) {
                    id = 1;
                } else {
                    do {
                        nextid = rs.getInt("invoice_id");
                        if (nextid - previousid == 1) {
                            previousid = nextid;
                        } else {
                            check = false;
                        }
                    } while (rs.next() && check);
                    if (check) {
                        id = nextid + 1;
                    } else {
                        id = previousid + 1;
                    }

                }
          String status;
              
                if (PaidCheck.isSelected())   
          {
          JOptionPane.showMessageDialog(null, "Hóa đơn đã được thanh toán.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
           status= "PAID";
           } else 
          {
   
    JOptionPane.showMessageDialog(null, "Hóa đơn hưa được thanh toán.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
   status= "UNPAID";
        }

 double total=Double.parseDouble(jtxtTotal.getText());
 int customerID=0;
    String payment=(String) jcboPayment.getSelectedItem();
    
   String cusName=customerNameF.getText();
   String findAccount="SELECT customerID FROM CUSTOMER WHERE Name=?";
   pstmt=conn.prepareStatement(findAccount);
   pstmt.setString(1, cusName);
   rs=pstmt.executeQuery();
   if(rs.next())
   {
      customerID=rs.getInt("customerID");
      
   }
   else{ 
             ArrayList<Object[]> tableData = new ArrayList<>();
              for (int i = 0; i < jTable1.getRowCount(); i++) {
              Object[] row = new Object[jTable1.getColumnCount()];
              for (int j = 0; j < jTable1.getColumnCount(); j++) {
              row[j] = jTable1.getValueAt(i, j);
                   }
               tableData.add(row);
            }
  
              String paymentMethod=(String)jcboPayment.getSelectedItem();
              String customerName=customerNameF.getText();
              String cash=jtxtDisplay.getText();
              boolean state=PaidCheck.isSelected();


 

            createAccount createAccount = new createAccount();
            createAccount.setNameF(cusName);   
            dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            productGUI productGUI = new productGUI();
            productGUI.setVisible(true);
            createAccount.setVisible(true);
            productGUI.setCustomerName(customerName);
            productGUI.setCash(cash);
            productGUI.setComboBox(paymentMethod);
            productGUI.setPaidCheck(state);
            productGUI.setTable(tableData);          
           }
            }
            );
           

                  return;
   }

   

String insertQuery = "INSERT INTO invoices (invoice_id, status, Date,Total_Price,payment,customerID) VALUES (?, ?, ?, ?,?,?)";
pstmt = conn.prepareStatement(insertQuery);

   pstmt.setInt(1, id); 
   pstmt.setString(2, status); 
   pstmt.setDate(3, new java.sql.Date(System.currentTimeMillis()));
   pstmt.setDouble(4, total);
   pstmt.setString(5, payment);
   pstmt.setInt(6, customerID);
    pstmt.executeUpdate();
    
     PreparedStatement insertStmt=null; 
     PreparedStatement find=null;
     PreparedStatement updateSale=null;
     
     DefaultTableModel  model=(DefaultTableModel) jTable1.getModel();
     
     String insert="INSERT INTO product_in_invoice(product_id,amount,invoice_id) values(?,?,?)";
     insertStmt=conn.prepareStatement(insert);
     
     String findProduct="Select productID from Products where Name=?";
     
     find=conn.prepareStatement(findProduct);
      String updateSaleQuery = 
        "UPDATE sale " +
        "SET quantity_sold = quantity_sold + ?, " +
        "    sale = sale + (? * (SELECT price FROM Products WHERE productID = ?)) " +
        "WHERE productID = ?";
      updateSale=conn.prepareStatement(updateSaleQuery);
      
     int productID=0;
     
     for(int i=0;i<model.getRowCount();i++){
              String name=(String) model.getValueAt(i,0);
              find.setString(1,name);
              rs=find.executeQuery();
              if(rs.next())    
              {
               productID=rs.getInt("productID");             
              }
              else
              {
                  JOptionPane.showMessageDialog(null,"CAN'T FIND THE PRODUCT");
              }
              int amount=(int) model.getValueAt(i,3);   
              
              insertStmt.setInt(1,productID);
              insertStmt.setInt(2,amount);
              insertStmt.setInt(3, id);
              insertStmt.executeUpdate();     
              
              
              updateSale.setInt(1,amount);
              updateSale.setInt(2,amount);
              updateSale.setInt(3, productID);
              updateSale.setInt(4,productID);
              updateSale.executeUpdate();
                          
             }
     
                       
            } catch (ClassNotFoundException | SQLException e) {
                e.printStackTrace();
            } finally{
                try {
                    if (pstmt != null)
                        pstmt.close();
                    if (conn != null && !conn.isClosed())
                        conn.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            
        MessageFormat header=new MessageFormat("Printing is progess");
        MessageFormat footer=new MessageFormat("Page in{0,number,integer}");
      try
      {
          jTable1.print(JTable.PrintMode.NORMAL,header,footer) ;         
      }catch(java.awt.print.PrinterException e){
          System.err.format("No Printer found",e.getMessage());
          
      }

    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
       DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
       int RemoveItem=jTable1.getSelectedRow();
       if(RemoveItem >=0)
       {
           model.removeRow(RemoveItem);
       }     
       ItemCost();
         if(jcboPayment.getSelectedItem().equals("cash"))
       {      
           Change(); 
       }
       else
       {
 
           jtxtChange.setText("");
           jtxtDisplay.setText("");
       }
    }//GEN-LAST:event_jbtnRemoveActionPerformed
     private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
      frame=new JFrame("Exit");
      if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Point of Sale",
      JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION);
      {
          System.exit(0);
          
      }
    }//GEN-LAST:event_jbtnExitActionPerformed

    
    public static String removeSpaces(String str) {
    // Sử dụng phương thức trim() để loại bỏ các khoảng trống từ đầu và cuối chuỗi
    // Sử dụng phương thức replaceAll() để loại bỏ tất cả các khoảng trống bên trong chuỗi
    return str.trim().replaceAll("\\s+", "");
}
    private void bathroomAccessoriesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bathroomAccessoriesBtnActionPerformed
    jPanel6.removeAll();
    jPanel6.setLayout(new GridLayout(3, 4));
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

   try {
      ImageIcon image=new ImageIcon("C:\\INVOICE BILLING SYSTEM\\src\\bathroomStuffs\\Wall Mounted Bathroom Trays Cosmetic Storage Rack for Home Toilet Bathroom Accessories.png");
       
    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
    String url = "jdbc:sqlserver://localhost:1433;databaseName=MOONHOUSE;user=sa;password=yennguyen@;encrypt=true;trustServerCertificate=true";
    conn = DriverManager.getConnection(url);
    String sql = "SELECT price,productID,Name,activate,category,supplier FROM PRODUCTS WHERE category='Bathroom'";
    pstmt = conn.prepareStatement(sql);
    rs = pstmt.executeQuery();
    
    while (rs.next()) {
        String name = rs.getString("Name");
        String category = rs.getString("category");
        double price = rs.getDouble("price");
        String activate=rs.getString("activate");
        JButton button = new JButton(name);

        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(customerNameF.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "ENTER THE CUSTOMER NAME!");
                }
                else{
                    if (activate.toLowerCase().contains(removeSpaces("yes"))) {
                        int existingRow = -1;
                for (int i = 0; i < model.getRowCount(); i++) {
                    if (name.equals(model.getValueAt(i, 0))) {
                   
                        existingRow = i;
                        break;
                    }
                }
                if (existingRow != -1) {
                 
                    int currentAmount = (int) model.getValueAt(existingRow, 3);
                    model.setValueAt(currentAmount + 1, existingRow, 3);
                    ItemCost();
                } else {
                    Object[] rowData = {name, category, price, 1}; 
                    model.addRow(rowData);
                    ItemCost();
                }

               
            }else{
                     JOptionPane.showMessageDialog(null, "THIS ITEM IS NOT AVAILABLE YET");
                    }
                }}});
        jPanel6.add(button);
    }
} catch (ClassNotFoundException | SQLException e) {
    e.printStackTrace();
} finally {
    // Đóng tài nguyên
    try {
        if (rs != null)
            rs.close();
        if (pstmt != null)
            pstmt.close();
        if (conn != null && !conn.isClosed())
            conn.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
   
    }//GEN-LAST:event_bathroomAccessoriesBtnActionPerformed

    @SuppressWarnings("empty-statement")
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

   bathroomAccessoriesBtn.doClick();
    }//GEN-LAST:event_formWindowOpened

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        if(Enternumber == "")
        {
            jtxtDisplay.setText(jbtn7.getText());
        }
        else
        {
            Enternumber=jtxtDisplay.getText()+ jbtn7.getText();
            jtxtDisplay.setText(Enternumber);

        }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void customerNameFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameFActionPerformed

    private void jtxtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChangeActionPerformed

    private void PaidCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaidCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaidCheckActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
  jPanel6.removeAll();
    jPanel6.setLayout(new GridLayout(5,3));
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

   try {
      ImageIcon image=new ImageIcon("C:\\INVOICE BILLING SYSTEM\\src\\bathroomStuffs\\Wall Mounted Bathroom Trays Cosmetic Storage Rack for Home Toilet Bathroom Accessories.png");
       
    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
    String url = "jdbc:sqlserver://localhost:1433;databaseName=MOONHOUSE;user=sa;password=yennguyen@;encrypt=true;trustServerCertificate=true";
    conn = DriverManager.getConnection(url);
    String sql = "SELECT price,productID,Name,activate,category,supplier FROM PRODUCTS WHERE category='Living Room Decor'";
    pstmt = conn.prepareStatement(sql);
    rs = pstmt.executeQuery();
    
    while (rs.next()) {
        String name = rs.getString("Name");
        String category = rs.getString("category");
        double price = rs.getDouble("price");
        String activate=rs.getString("activate");
        JButton button = new JButton(name);

        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(customerNameF.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "ENTER THE CUSTOMER NAME!");
                }
                else{
                    if ((activate.toLowerCase().contains(removeSpaces("yes")))) {
                        int existingRow = -1;
                for (int i = 0; i < model.getRowCount(); i++) {
                    if (name.equals(model.getValueAt(i, 0))) {
                   
                        existingRow = i;
                        break;
                    }
                }
                if (existingRow != -1) {
                 
                    int currentAmount = (int) model.getValueAt(existingRow, 3);
                    model.setValueAt(currentAmount + 1, existingRow, 3);
                    ItemCost();
                } else {
                    Object[] rowData = {name, category, price, 1}; 
                    model.addRow(rowData);
                    ItemCost();
                }

               
            }else{
                     JOptionPane.showMessageDialog(null, "THIS ITEM IS NOT AVAILABLE YET");
                    }
                }}});
        jPanel6.add(button);
    }
} catch (ClassNotFoundException | SQLException e) {
    e.printStackTrace();
} finally {
    // Đóng tài nguyên
    try {
        if (rs != null)
            rs.close();
        if (pstmt != null)
            pstmt.close();
        if (conn != null && !conn.isClosed())
            conn.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
     jPanel6.removeAll();
    jPanel6.setLayout(new GridLayout(5,3));
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

   try {
      ImageIcon image=new ImageIcon("C:\\INVOICE BILLING SYSTEM\\src\\bathroomStuffs\\Wall Mounted Bathroom Trays Cosmetic Storage Rack for Home Toilet Bathroom Accessories.png");
       
    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
    String url = "jdbc:sqlserver://localhost:1433;databaseName=MOONHOUSE;user=sa;password=123456;encrypt=true;trustServerCertificate=true";
    conn = DriverManager.getConnection(url);
    String sql = "SELECT price,productID,Name,activate,category,supplier FROM PRODUCTS WHERE category='Kitchenware'";
    pstmt = conn.prepareStatement(sql);
    rs = pstmt.executeQuery();
    
    while (rs.next()) {
        String name = rs.getString("Name");
        String category = rs.getString("category");
        double price = rs.getDouble("price");
        String activate=rs.getString("activate");
        JButton button = new JButton(name);

        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(customerNameF.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "ENTER THE CUSTOMER NAME!");
                }
                else{
                    if (activate.toLowerCase().contains(removeSpaces("yes"))) {
                        int existingRow = -1;
                for (int i = 0; i < model.getRowCount(); i++) {
                    if (name.equals(model.getValueAt(i, 0))) {
                   
                        existingRow = i;
                        break;
                    }
                }
                if (existingRow != -1) {
                 
                    int currentAmount = (int) model.getValueAt(existingRow, 3);
                    model.setValueAt(currentAmount + 1, existingRow, 3);
                    ItemCost();
                } else {
                    Object[] rowData = {name, category, price, 1}; 
                    model.addRow(rowData);
                    ItemCost();
                }

               
            }else{
                     JOptionPane.showMessageDialog(null, "THIS ITEM IS NOT AVAILABLE YET");
                    }
                }}});
        jPanel6.add(button);
    }
} catch (ClassNotFoundException | SQLException e) {
    e.printStackTrace();
} finally {
    // Đóng tài nguyên
    try {
        if (rs != null)
            rs.close();
        if (pstmt != null)
            pstmt.close();
        if (conn != null && !conn.isClosed())
            conn.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new menu().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

  

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox PaidCheck;
    private javax.swing.JRadioButton bathroomAccessoriesBtn;
    private javax.swing.JPanel btnlist;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField customerNameF;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JButton jtbtnPay;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDiscount;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
